/** The three question formats the game uses. */
export type QuestionType = 'type-in' | 'multi-choice' | 'multi-select'

/**
 * A single option in a multi-choice or multi-select question.
 * "Not applicable" is always one of the choices and is never correct.
 */
export interface Choice {
  id: string
  text: string
  isCorrect: boolean
}

/**
 * A question generated by AI alongside a story.
 * Questions are associated with a specific story but asked during a later story.
 */
export interface Question {
  id: string
  /** The story this question is about (not necessarily when it's asked). */
  storyId: string
  questionText: string
  questionType: QuestionType
  /** Answer string for type-in questions. Null for choice-based questions. */
  correctAnswer: string | null
  /** 7 choices + 1 "Not applicable" for multi-choice / multi-select. Null for type-in. */
  choices: Choice[] | null
  /**
   * If true, this is a MemoryPrompt — shown BEFORE the story begins as an instruction
   * ("Remember: the detective's name and the vault code") rather than a mid-read question.
   */
  isMemoryPrompt: boolean
  /**
   * If set, show this question after this specific paragraph index during its own story.
   * Only used for story-1 mid-read questions. Null = scheduled by questionScheduler.
   */
  triggerAfterParagraph: number | null
}

/**
 * A question placed into the session timeline by the question scheduler.
 * Defines exactly when (which story, which paragraph break) the question appears.
 */
export interface ScheduledQuestion {
  question: Question
  /** Which story (1-based) this question is about. */
  aboutStoryOrder: number
  /**
   * Which story (1-based) the user is reading when this question appears.
   * atStoryOrder === stories.length + 1 means "show on results screen".
   */
  atStoryOrder: number
  /**
   * Show after this paragraph index.
   * -1 = show before the story begins (MemoryPrompt).
   */
  atParagraphIndex: number
}
